#!/bin/sh
# Function To Extract File Archives Of Various Types
extract () {
     if [ -f "$1" ] ; then
         case $1 in
             *.tar.bz2)   tar xjf "$1"     ;;
             *.tar.gz | *.tar.xz)    tar xzf "$1"     ;;
             *.bz2)       bunzip2  "$1"    ;;
             *.rar)       rar x "$1"       ;;
             *.gz)        gunzip "$1"      ;;
             *.tar)       tar xf "$1"      ;;
             *.tbz2)      tar xjf "$1"     ;;
             *.tgz)       tar xzf "$1"     ;;
             *.zip)       unzip "$1"       ;;
             *.Z)         uncompress "$1"  ;;
             *.7z)        7z x "$1"        ;;
             *)           echo "'$1' cannot be extracted via extract()" ;;
         esac
     else
         echo "'$1' is not a valid file"
     fi
}
# find alias more easy
aliases() {
    alias | grep "$1"
}

dm() {
    BASE="$HOME/Dev/DigitalMagazine"
    initnvm() {
        NVM_DIR="$HOME/.local/share/nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && nvm use 12.14.0
    }
    cdm() { cd "$BASE" ; }
    case $1 in
        # Actions
        sheet) qutebrowser "" ;; 
        pres) qutebrowser "" ;; 
        init) initnvm ;;
        start) cdm && initnvm && npm run dev ;; 
        stat) cdm && ls && git status ;; 
        edit) cdm && nvim -c "Telescope find_files" ;; 
        # Directories
        db) cd "$BASE/src/app/shared/services/Db" && ls ;; 
        models) cd "$BASE/src/app/shared/services/Db/Models" && ls ;; 
        auth) cd "$BASE/src/app/shared/modules/auth" && ls ;; 
        app) cd "$BASE/src/app" && ls ;; 
        *) cdm && ls ;;
    esac
}
