#!/bin/sh

export EDITOR="nvim"
export BROWSER="librewolf"
export SHELPER="$HOME/.local/bin/shelper"

export FUN_SOUNDS="anything"

export PATH="${PATH}":"${XDG_DATA_HOME}/npm/bin":"${HOME}/.local/bin":"${HOME}/.local/bin/dmenu":"${HOME}/.local/bin/dwm-bar":/usr/share/bin:/opt/VStudio
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
#export LESSHISTFILE=- # enable to disable this feature
export CARGO_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/cargo"
export PYTHONHISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/python/history"
export SUDO_ASKPASS="$HOME"/.local/bin/dmenu/dpass
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export SSB_HOME="$XDG_DATA_HOME"/zoom
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export MYSQL_HISTFILE="$XDG_DATA_HOME"/mysql_history
export GOPATH="$XDG_DATA_HOME"/go
export ANDROID_HOME="$XDG_DATA_HOME"/android
export HISTFILE="${XDG_CACHE_HOME}"/zsh/history
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export PSQL_HISTORY="$XDG_DATA_HOME/psql_history"
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export VIMINIT='let $MYVIMRC = !has("nvim") ? "$XDG_CONFIG_HOME/vim/vimrc" : "$XDG_CONFIG_HOME/nvim/init.lua" | so $MYVIMRC'

# Java, android, flutter
export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions'
export JAVA_HOME='/usr/lib/jvm/java-8-openjdk'
export ANDROID_SDK_ROOT='/opt/android-sdk'
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle

# Colors for fzf, maybe will move in another place
# Source: rose-pine theme
export FZF_DEFAULT_OPTS="
	--color=fg:#908caa,bg:#000000,hl:#ebbcba
	--color=fg+:#e0def4,bg+:#000000,hl+:#ebbcba
	--color=border:#403d52,header:#31748f,gutter:#191724
	--color=spinner:#f6c177,info:#9ccfd8,separator:#403d52
	--color=pointer:#c4a7e7,marker:#eb6f92,prompt:#908caa"
