#!/bin/sh

export EDITOR="vim"
export BROWSER="librewolf"

export XDG_DATA_HOME="$HOME/.local/share"
export PATH=${PATH}:${XDG_DATA_HOME}/npm/bin:${HOME}/.local/bin:${HOME}/.local/bin/dmenu:${HOME}/.local/bin/dwm-bar:/usr/share/bin
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
#export LESSHISTFILE=- # enable to disable this feature
export CARGO_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/cargo"
export PYTHONHISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/python/history"
export SUDO_ASKPASS=$HOME/.local/bin/dmenu/dpass
export ERRFILE="$XDG_CACHE_HOME/x11/xsession-errors"
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export SSB_HOME="$XDG_DATA_HOME"/zoom
